# app = "brandemen-chat"  # Will be set during launch
primary_region = "iad"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "3000"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
